public with sharing class Book {
  String str = 'ran';

  Double doubles = 2.0;

  Boolean bools = true;

  Object obj = 'ran';

  Object objnull = null;

  Integer[] ints2 = new List<Integer>{ 1, 2, 3, 5 };

  List<String> listName = new List<String>{ 'ranjith', 'mouni' };

  List<Integer> ints = new List<Integer>{ 1, 2, 3, 4 };

  Map<String, Object> dates = new Map<String, Object>{
    '1' => 'ranjith',
    '2' => 'mouni'
  };
}
